name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-both:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
  build-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
        working-directory: a
  build-b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
        working-directory: b
